name:                SHIFT
version:             0.1.0.0
github:              "githubuser/SHIFT"
license:             BSD-2-Clause
author:              "Asher Frost"
maintainer:          "example@example.com"
copyright:           "2025 Asher Frost"

flags: 
  dev: 
    default: false 
    manual: false
extra-source-files:
- README.md
- CHANGELOG.md
extra-doc-files:
- docs/*
- paper/*

language: GHC2021
description:         Please see the README on GitHub at <https://github.com/githubuser/SHIFT#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- mtl
- megaparsec

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

when:
  condition: flag(dev)
  ghc-options:
    -fdefer-typed-holes

library:
  source-dirs: src
  exposed-modules:
  - Rift
  - Sift 
  - Lift
  - Extra

executables:
  SHIFT-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SHIFT

tests:
  SHIFT-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SHIFT
