/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 21
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI_SEMI_SEMI = 1,
  anon_sym_SEMI = 2,
  anon_sym_LPAREN = 3,
  anon_sym_RPAREN = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  anon_sym_LBRACE = 7,
  anon_sym_RBRACE = 8,
  sym_wildcard = 9,
  sym_identifier = 10,
  sym_source_file = 11,
  sym_theory = 12,
  sym_sentence = 13,
  sym_term = 14,
  sym_cons = 15,
  sym_lamed = 16,
  sym_atomic = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_theory_repeat1 = 19,
  aux_sym_cons_repeat1 = 20,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI_SEMI_SEMI] = ";;;",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_wildcard] = "wildcard",
  [sym_identifier] = "identifier",
  [sym_source_file] = "source_file",
  [sym_theory] = "theory",
  [sym_sentence] = "sentence",
  [sym_term] = "term",
  [sym_cons] = "cons",
  [sym_lamed] = "lamed",
  [sym_atomic] = "atomic",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_theory_repeat1] = "theory_repeat1",
  [aux_sym_cons_repeat1] = "cons_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI_SEMI_SEMI] = anon_sym_SEMI_SEMI_SEMI,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_wildcard] = sym_wildcard,
  [sym_identifier] = sym_identifier,
  [sym_source_file] = sym_source_file,
  [sym_theory] = sym_theory,
  [sym_sentence] = sym_sentence,
  [sym_term] = sym_term,
  [sym_cons] = sym_cons,
  [sym_lamed] = sym_lamed,
  [sym_atomic] = sym_atomic,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_theory_repeat1] = aux_sym_theory_repeat1,
  [aux_sym_cons_repeat1] = aux_sym_cons_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI_SEMI_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_theory] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_term] = {
    .visible = true,
    .named = true,
  },
  [sym_cons] = {
    .visible = true,
    .named = true,
  },
  [sym_lamed] = {
    .visible = true,
    .named = true,
  },
  [sym_atomic] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_theory_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_cons_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 8,
  [11] = 11,
  [12] = 11,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 20,
  [26] = 22,
  [27] = 21,
  [28] = 28,
  [29] = 29,
  [30] = 19,
  [31] = 28,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '(', 7,
        ')', 8,
        ';', 6,
        '[', 9,
        ']', 10,
        '_', 13,
        '{', 11,
        '}', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ';') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == ';') ADVANCE(1);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == ';') ADVANCE(2);
      if (lookahead == '[') ADVANCE(9);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == '}') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(15);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_SEMI_SEMI_SEMI);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_identifier);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ';' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '_' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(29),
    [sym_theory] = STATE(2),
    [sym_sentence] = STATE(5),
    [sym_term] = STATE(32),
    [sym_cons] = STATE(25),
    [sym_lamed] = STATE(25),
    [sym_atomic] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_theory_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_theory] = STATE(3),
    [sym_sentence] = STATE(5),
    [sym_term] = STATE(32),
    [sym_cons] = STATE(25),
    [sym_lamed] = STATE(25),
    [sym_atomic] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_theory_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_theory] = STATE(3),
    [sym_sentence] = STATE(5),
    [sym_term] = STATE(32),
    [sym_cons] = STATE(25),
    [sym_lamed] = STATE(25),
    [sym_atomic] = STATE(25),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_theory_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(20),
    [sym_wildcard] = ACTIONS(23),
    [sym_identifier] = ACTIONS(26),
  },
  [STATE(4)] = {
    [sym_term] = STATE(4),
    [sym_cons] = STATE(20),
    [sym_lamed] = STATE(20),
    [sym_atomic] = STATE(20),
    [aux_sym_cons_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(32),
    [anon_sym_LBRACK] = ACTIONS(34),
    [anon_sym_RBRACK] = ACTIONS(32),
    [anon_sym_RBRACE] = ACTIONS(32),
    [sym_wildcard] = ACTIONS(37),
    [sym_identifier] = ACTIONS(40),
  },
  [STATE(5)] = {
    [sym_sentence] = STATE(6),
    [sym_term] = STATE(32),
    [sym_cons] = STATE(25),
    [sym_lamed] = STATE(25),
    [sym_atomic] = STATE(25),
    [aux_sym_theory_repeat1] = STATE(6),
    [anon_sym_SEMI_SEMI_SEMI] = ACTIONS(43),
    [anon_sym_LPAREN] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_wildcard] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
  },
  [STATE(6)] = {
    [sym_sentence] = STATE(6),
    [sym_term] = STATE(32),
    [sym_cons] = STATE(25),
    [sym_lamed] = STATE(25),
    [sym_atomic] = STATE(25),
    [aux_sym_theory_repeat1] = STATE(6),
    [anon_sym_SEMI_SEMI_SEMI] = ACTIONS(45),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(50),
    [sym_wildcard] = ACTIONS(53),
    [sym_identifier] = ACTIONS(56),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      anon_sym_RPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [25] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [50] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(71), 1,
      anon_sym_RPAREN,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [75] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [100] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(75), 1,
      anon_sym_RBRACK,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [125] = 7,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(77), 1,
      anon_sym_RBRACK,
    STATE(4), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [150] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(9), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [172] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(7), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [194] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(11), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [216] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(8), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [238] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(10), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [260] = 6,
    ACTIONS(59), 1,
      anon_sym_LPAREN,
    ACTIONS(63), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      sym_wildcard,
    ACTIONS(67), 1,
      sym_identifier,
    STATE(12), 2,
      sym_term,
      aux_sym_cons_repeat1,
    STATE(20), 3,
      sym_cons,
      sym_lamed,
      sym_atomic,
  [282] = 2,
    ACTIONS(81), 1,
      sym_identifier,
    ACTIONS(79), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_wildcard,
  [294] = 2,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(83), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_wildcard,
  [306] = 2,
    ACTIONS(89), 1,
      sym_identifier,
    ACTIONS(87), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_wildcard,
  [318] = 2,
    ACTIONS(93), 1,
      sym_identifier,
    ACTIONS(91), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      sym_wildcard,
  [330] = 2,
    ACTIONS(95), 2,
      ts_builtin_sym_end,
      sym_identifier,
    ACTIONS(97), 3,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_wildcard,
  [340] = 2,
    ACTIONS(101), 1,
      sym_identifier,
    ACTIONS(99), 4,
      anon_sym_SEMI_SEMI_SEMI,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_wildcard,
  [350] = 1,
    ACTIONS(85), 1,
      anon_sym_SEMI,
  [354] = 1,
    ACTIONS(93), 1,
      anon_sym_SEMI,
  [358] = 1,
    ACTIONS(89), 1,
      anon_sym_SEMI,
  [362] = 1,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
  [366] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [370] = 1,
    ACTIONS(81), 1,
      anon_sym_SEMI,
  [374] = 1,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
  [378] = 1,
    ACTIONS(109), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 25,
  [SMALL_STATE(9)] = 50,
  [SMALL_STATE(10)] = 75,
  [SMALL_STATE(11)] = 100,
  [SMALL_STATE(12)] = 125,
  [SMALL_STATE(13)] = 150,
  [SMALL_STATE(14)] = 172,
  [SMALL_STATE(15)] = 194,
  [SMALL_STATE(16)] = 216,
  [SMALL_STATE(17)] = 238,
  [SMALL_STATE(18)] = 260,
  [SMALL_STATE(19)] = 282,
  [SMALL_STATE(20)] = 294,
  [SMALL_STATE(21)] = 306,
  [SMALL_STATE(22)] = 318,
  [SMALL_STATE(23)] = 330,
  [SMALL_STATE(24)] = 340,
  [SMALL_STATE(25)] = 350,
  [SMALL_STATE(26)] = 354,
  [SMALL_STATE(27)] = 358,
  [SMALL_STATE(28)] = 362,
  [SMALL_STATE(29)] = 366,
  [SMALL_STATE(30)] = 370,
  [SMALL_STATE(31)] = 374,
  [SMALL_STATE(32)] = 378,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cons_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_cons_repeat1, 2, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cons_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_cons_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_cons_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_theory_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_theory_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_theory_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_theory_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_theory_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atomic, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atomic, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_term, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_term, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lamed, 6, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lamed, 6, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cons, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cons, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_theory, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_theory, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_sentence, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tift(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tift",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
